# This configuration is used in the 'label-manager' workflow
# Examples from https://github.com/actions/labeler?tab=readme-ov-file#basic-examples
# This file is sourced from the 'infra' repo, the file location is: 'infra/assets/dot_gh/labeler.yml.j2'

actions:autorelease:
- any:
  - head-branch: ['^autorelease','autorelease']

actions:dependabot:
- any:
  - head-branch: ['^dependabot','dependabot']

documentation:
- all:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md','**/docs/*','docs/**','examples/**']
    - all-globs-to-all-files: '!CHANGELOG.md'

impacts:assets:
- any:
  - changed-files:
    - any-glob-to-any-file: ['assets/**', 'infra/assets/**']

impacts:infra:
- any:
  - changed-files:
    - any-glob-to-any-file: 'infra/**'

impacts:repo:
- all:
  - changed-files:
    - any-glob-to-any-file: '.github/**'
    - all-globs-to-all-files: '!.github/workflows/**'

impacts:workflows:
- any:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'
