name: Autorelease 03 - Build Prod
run-name: 'Build prod image'

on: 
  push:
    tags:
      - 'v*.*.*'

permissions:
  #contents: read
  contents: write
  #issues: write
  #pull-requests: write

jobs:

  print-tag-info:
    #name: print-tag-info
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.release-vars-output.outputs.RELEASE_VERSION }}
    if: (github.repository_owner == 'rwaight')
    #if: | 
    #  (github.repository_owner == 'rwaight') &&
    #  (github.event_name=='release' && github.event.action=='published')
    env:
      VERBOSE: ${{ inputs.debug_output || 'true' }}
    steps:
      - name: Checkout files from commit tree
        # Verified creator: https://github.com/marketplace/actions/checkout
        # GitHub Action for checking out a repo
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Get release version
        id: get-release-version
        #if: (github.ref_type == 'tag')
        run: |
          echo "starting step 'get-release-version' "
          VERSION="${{ github.event.release.tag_name || github.ref_name }}"
          ##
          RE='^[vV]?([0-9]+)[.]([0-9]+)[.]([0-9]+)(-[0-9A-Za-z.+-]*)?'
          if [[ $VERSION =~ $RE ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            PRERELEASE="${BASH_REMATCH[4]}"
          else
            echo "::error::Version '$VERSION' is not in a valid format"
            exit 1
          fi
          ##
          if [[ "$PRERELEASE" ]]; then pre=true; else pre=false; fi
          ##
          echo "full-version-ref=$VERSION" >> $GITHUB_OUTPUT
          echo "major-ref=v$MAJOR" >> $GITHUB_OUTPUT
          echo "minor-ref=v$MINOR" >> $GITHUB_OUTPUT
          echo "patch-ref=v$PATCH" >> $GITHUB_OUTPUT
          echo "is-prerelease=$pre" >> $GITHUB_OUTPUT
          echo "completing the 'get-release-version' step "

      - name: Set MY_REF and RELEASE_VERSION environmental variable and output
        id: release-vars-output
        run: |
          echo "MY_REF=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "MY_REF=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Check output from get-release-version and release-vars-output
        id: check-different-outputs
        env:
          FULL_VERSION_REF: ${{ steps.get-release-version.outputs.full-version-ref }}
          MAJOR_REF: ${{ steps.get-release-version.outputs.major-ref }}
          MINOR_REF: ${{ steps.get-release-version.outputs.minor-ref }}
          PATCH_REF: ${{ steps.get-release-version.outputs.patch-ref }}
          IS_PRERELEASE: ${{ steps.get-release-version.outputs.is-prerelease }}
          REFS_VERSION: ${GITHUB_REF#refs/*/}
          MY_REF: ${{ steps.release-vars-output.outputs.MY_REF }}
          RELEASE_VERSION: ${{ steps.release-vars-output.outputs.RELEASE_VERSION }}
        run: |
          echo "starting step 'check-different-outputs' "
          echo ""
          echo "## REFS_VERSION variables"
          echo ${{ env.REFS_VERSION }}
          echo $REFS_VERSION
          echo ""
          echo "## release-vars-output outputs"
          echo "MY_REF         :  ${{ env.MY_REF }} "
          echo "RELEASE_VERSION:  ${{ env.RELEASE_VERSION }} "
          echo ""
          echo ${{ steps.release-vars-output.outputs.MY_REF }}
          echo ${{ steps.release-vars-output.outputs.RELEASE_VERSION }}
          echo ""
          echo "## get-release-version outputs"
          echo "Full version: ${{ env.FULL_VERSION_REF }} "
          echo "Major ref   : ${{ env.MAJOR_REF }} "
          echo "Minor ref   : ${{ env.MINOR_REF }} "
          echo "Patch ref   : ${{ env.PATCH_REF }} "
          echo "Prerelease  : ${{ env.IS_PRERELEASE }}"
          echo ""
          echo "completing the 'check-different-outputs' step. "

      - name: Check output of MY_REF and RELEASE_VERSION
        env:
          MY_REF: ${{ steps.release-vars-output.outputs.MY_REF }}
          RELEASE_VERSION: ${{ steps.release-vars-output.outputs.RELEASE_VERSION }}
        run: |
          echo "## RELEASE_VERSION variables"
          echo ${{ env.RELEASE_VERSION }}
          echo $RELEASE_VERSION
          echo ${{ steps.release-vars-output.outputs.RELEASE_VERSION }}
          echo ""
          echo "## MY_REF variables"
          echo ${{ env.MY_REF }}
          echo $MY_REF
          echo ${{ steps.release-vars-output.outputs.MY_REF }}
          echo ""

      - name: This should run when there are tags pushed
        if: github.ref_type == 'tag'
        run: |
          echo "release tag_name: ${{ github.event.release.tag_name }} "
          echo ""
          echo "Event name:  ${{ github.event_name }} "
          echo "Ref       :  ${{ github.ref }} "
          echo "Ref name  :  ${{ github.ref_name }} "
          echo "Ref type  :  ${{ github.ref_type }} "

      - name: This should run when a release is published
        if: ${{ github.event.release.tag_name }}
        run: |
          echo "release tag_name: ${{ github.event.release.tag_name }} "
          echo ""
          echo "Event name:  ${{ github.event_name }} "
          echo "Ref       :  ${{ github.ref }} "
          echo "Ref name  :  ${{ github.ref_name }} "
          echo "Ref type  :  ${{ github.ref_type }} "

      - name: Run workflow debug
        id: run-workflow-debug
        if: env.VERBOSE=='true'
        run: |
          echo "workflow verbose was set to true... you should probably put something here for debug purposes. "
          echo ""
          echo "release tag_name: ${{ github.event.release.tag_name }} "
          echo ""
          echo "Event name:  ${{ github.event_name }} "
          echo "Ref       :  ${{ github.ref }} "
          echo "Ref name  :  ${{ github.ref_name }} "
          echo "Ref type  :  ${{ github.ref_type }} "
          echo ""
          echo "For more information, see the GitHub Actions Contexts docs, which are located at: "
          echo "https://docs.github.com/en/actions/learn-github-actions/contexts#github-context"
          echo "The 'run-workflow-debug' step is now complete. "
        continue-on-error: true

      - name: Prerelease notice
        if: fromJSON(steps.get-release-version.outputs.is-prerelease)
        run: |
          echo "::notice::Pre-release version detected, not moving major ref ${{ steps.get-release-version.outputs.major-ref }}"
          echo "::notice::Pre-release version detected, not moving minor ref ${{ steps.get-release-version.outputs.minor-ref }}"
