# this workflow is an example from:  https://github.com/orgs/community/discussions/26639#discussioncomment-3949595
# 'Workflow job with needs output from matrix?'
name: matrix-job-output-test-01
run-name: Does test-01 work?
on:
  push:
    branches: ["**"]

jobs:
  parallel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        option:
          - a
          - b

    steps:
      - name: output
        id: output
        run: |
          echo "${{ matrix.option }}=${{ matrix.option }}" >> $GITHUB_OUTPUT

    outputs:
      a: ${{ steps.output.outputs.a }}
      b: ${{ steps.output.outputs.b }}

  finally:
    needs: parallel
    runs-on: ubuntu-latest

    strategy:
      matrix:
        option: ${{ needs.parallel.outputs.* }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: debug
        run: echo '${{ toJSON(needs.parallel.outputs) }}'
