# This workflow currently runs the 'pr-labeler' action
name: Test PR Manager
run-name: Run PR Manager on ${{ github.event_name }}
on:
  pull_request:
    # 'on pull_request' is used by: 'pr-labeler'
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  workflow_dispatch:
    # inputs:
    #   debug_output:
    #     description: 'Debug output'
    #     required: true
    #     default: false
    #     type: boolean



jobs:
  pr-labeler:
    name: Label pull requests
    runs-on: ubuntu-latest
    #if: (github.event_name == 'pull_request')
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Exit workflow in forked repo
        id: check-repo-owner
        if: (github.repository_owner != 'rwaight')
        run: |
          echo "This workflow was run in a forked repo. Unless this file is updated, none of the jobs will run. "
          echo "This workflow will now exit. "
          exit 0

      # https://github.com/actions/create-github-app-token
      - name: Creating a GitHub App Token
        #uses: actions/create-github-app-token@v1
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        id: app-token
        with:
          # required
          app-id: ${{ secrets.RW_ACTIONS_APP_ID }}
          private-key: ${{ secrets.RW_ACTIONS_APP_KEY }}

      - name: Checkout files from commit tree
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          #token: ${{ github.token }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Apply non-versioning labels
        id: label-pull-request
        uses: actions/labeler@v5
        with:
          repo-token: ${{ steps.app-token.outputs.token }}

      - name: Check for semantic version labels
        #uses: docker://agilepathway/pull-request-label-checker:latest
        uses: rwaight/actions/test/check-semver-labels@main
        #uses: rwaight/actions/github/label-checker@main # can use version specific or main
        #uses: rwaight/actions/github/label-checker@v1
        id: check-semver-labels
        with:
          gh-token: ${{ steps.app-token.outputs.token }}
          allow_failure: true
          semver-fallback: 'triage:version-needed'
          semver-prefix: 'version:'
          my_action_debug: true

